// tcp_http_test.go proves the whole point of this plan (ROADMAP Phase 3
// success criterion 3's first clause, NET-02): unmodified stdlib
// http.Serve accepts on Stack.ListenTCP's listener and serves a complete
// HTTP/1.1 request/response to an unmodified stdlib http.Client — no
// hand-rolled request strings, no wrapper, no adapter around net/http
// itself.
//
// netTestConn below is the bridge: a real net.Conn built over plan 03-03's
// minimal test TCP client (tcpclient_test.go), so the request bytes are
// generated by stdlib net/http and the response bytes are parsed by
// stdlib net/http. It is deliberately a SECOND, independent implementation
// from the production tcpConn (tcp_conn.go) — sharing code with the thing
// under test would let a symmetric bug cancel out undetected, mirroring
// tcpclient_test.go's own house rule.
package netstack

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// netTestConn adapts a *tcpTestClient into a real net.Conn. Deadlines are
// deliberately minimal (no-ops): this is the TEST's own side of the wire,
// not the production conn under test — RESEARCH.md's own plan text notes
// "deadlines may be minimal since the client side is the test's own".
type netTestConn struct {
	c *tcpTestClient

	mu      sync.Mutex
	cond    *sync.Cond
	buf     []byte
	peerFIN bool
	err     error

	closeOnce   sync.Once
	localClosed bool

	localAddr  net.Addr
	remoteAddr net.Addr
}

var _ net.Conn = (*netTestConn)(nil)

// newNetTestConn wraps an already-connected tcpTestClient (its handshake
// must already be complete) and starts the background segment-reading loop
// that ACKs inbound data/FIN and buffers payload for Read.
func newNetTestConn(c *tcpTestClient) *netTestConn {
	nc := &netTestConn{
		c:          c,
		localAddr:  &net.TCPAddr{IP: net.IP(c.localIP.AsSlice()), Port: int(c.localPort)},
		remoteAddr: &net.TCPAddr{IP: net.IP(c.remoteIP.AsSlice()), Port: int(c.remotePort)},
	}
	nc.cond = sync.NewCond(&nc.mu)
	go nc.readLoop()
	return nc
}

// readLoop drains the fake session's outbound channel, ACKing every
// data-or-FIN segment it consumes (cumulative ACK, matching a real client)
// and buffering payload bytes for Read. It exits once the peer's FIN is
// consumed, an RST arrives, or the underlying recvRaw times out (the fake
// session was closed/torn down).
func (nc *netTestConn) readLoop() {
	for {
		seg, ok := nc.c.tryRecvRaw(10 * time.Second)
		if !ok {
			nc.mu.Lock()
			if nc.err == nil {
				nc.err = io.ErrClosedPipe
			}
			nc.cond.Broadcast()
			nc.mu.Unlock()
			return
		}
		if seg.flags&flagRST != 0 {
			nc.mu.Lock()
			nc.err = errors.New("netTestConn: received RST from server")
			nc.cond.Broadcast()
			nc.mu.Unlock()
			return
		}

		dataLen := len(seg.payload)
		nc.mu.Lock()
		consumesSeq := dataLen > 0 || seg.flags&flagFIN != 0
		if !consumesSeq || seg.seq != nc.c.rcvNext {
			// A bare ACK, or (this fake medium never reorders/drops)
			// something out of order — nothing new to deliver.
			nc.mu.Unlock()
			continue
		}
		if dataLen > 0 {
			nc.buf = append(nc.buf, seg.payload...)
			nc.c.rcvNext += uint32(dataLen)
		}
		peerFIN := false
		if seg.flags&flagFIN != 0 {
			nc.c.rcvNext++
			nc.peerFIN = true
			peerFIN = true
		}
		ackSeg := tcpSegment{
			srcPort: nc.c.localPort,
			dstPort: nc.c.remotePort,
			seq:     nc.c.sndNext,
			ack:     nc.c.rcvNext,
			flags:   flagACK,
			window:  65535,
		}
		nc.cond.Broadcast()
		nc.mu.Unlock()

		nc.c.sendRaw(ackSeg)

		if peerFIN {
			return
		}
	}
}

// Read implements net.Conn: ordinary streaming semantics, blocking until
// data is available, the peer's FIN has been consumed (io.EOF), or the
// connection has failed.
func (nc *netTestConn) Read(p []byte) (int, error) {
	nc.mu.Lock()
	defer nc.mu.Unlock()
	for len(nc.buf) == 0 {
		if nc.err != nil {
			return 0, nc.err
		}
		if nc.peerFIN {
			return 0, io.EOF
		}
		nc.cond.Wait()
	}
	n := copy(p, nc.buf)
	nc.buf = nc.buf[n:]
	return n, nil
}

// Write implements net.Conn: segments p by the server's advertised MSS
// (from the handshake) and sends immediately — the fake session is a
// reliable, in-order, lossless medium in these tests, so no
// retransmission/windowing logic is needed on this side.
//
// nc.mu is held only long enough to check state and to read/advance
// sndNext for each chunk — NEVER across the sendRaw call itself. sendRaw
// pushes onto the fake session's bounded inbound channel and blocks once
// it's full; holding nc.mu across that block would deadlock against
// readLoop, which also needs nc.mu to process the resulting ACKs (and, in
// turn, to drain the fake session's outbound channel that the server's own
// write path is blocked on) — an early version of this file hung exactly
// this way on TestHTTPLargeRequestBody.
func (nc *netTestConn) Write(p []byte) (int, error) {
	nc.mu.Lock()
	if nc.err != nil {
		err := nc.err
		nc.mu.Unlock()
		return 0, err
	}
	if nc.localClosed {
		nc.mu.Unlock()
		return 0, errors.New("netTestConn: write after close")
	}
	mss := int(nc.c.serverMSS)
	nc.mu.Unlock()
	if mss <= 0 {
		mss = 1400
	}

	total := 0
	for total < len(p) {
		chunk := p[total:]
		if len(chunk) > mss {
			chunk = chunk[:mss]
		}

		nc.mu.Lock()
		seg := tcpSegment{
			srcPort: nc.c.localPort,
			dstPort: nc.c.remotePort,
			seq:     nc.c.sndNext,
			ack:     nc.c.rcvNext,
			flags:   flagACK,
			window:  65535,
			payload: chunk,
		}
		nc.c.sndNext += uint32(len(chunk))
		nc.mu.Unlock()

		nc.c.sendRaw(seg)
		total += len(chunk)
	}
	return total, nil
}

// Close implements net.Conn: sends this side's own FIN exactly once.
func (nc *netTestConn) Close() error {
	nc.closeOnce.Do(func() {
		nc.mu.Lock()
		nc.localClosed = true
		seg := tcpSegment{
			srcPort: nc.c.localPort,
			dstPort: nc.c.remotePort,
			seq:     nc.c.sndNext,
			ack:     nc.c.rcvNext,
			flags:   flagFIN | flagACK,
			window:  65535,
		}
		nc.c.sndNext++
		nc.mu.Unlock()
		nc.c.sendRaw(seg)
	})
	return nil
}

func (nc *netTestConn) LocalAddr() net.Addr  { return nc.localAddr }
func (nc *netTestConn) RemoteAddr() net.Addr { return nc.remoteAddr }

// SetDeadline/SetReadDeadline/SetWriteDeadline are deliberate no-ops: this
// is the test's own side of the wire, not the production conn under test.
func (nc *netTestConn) SetDeadline(t time.Time) error      { return nil }
func (nc *netTestConn) SetReadDeadline(t time.Time) error  { return nil }
func (nc *netTestConn) SetWriteDeadline(t time.Time) error { return nil }

// dialTCPTestConn attaches a fresh fake session under clientIP and drives a
// full TCP handshake against stack's listener on port using ONLY non-fatal
// primitives (tryRecvRaw, never recvRaw/connect, neither of which may call
// t.Fatal). This function runs inside http.Transport's own
// internally-spawned dial goroutine, not the test's own goroutine — the
// testing package's own contract is that FailNow (which t.Fatal calls)
// "must be called from the goroutine running the test... function, not
// from other goroutines created during the test"; calling it here left an
// early version of this harness hung forever, since the dial goroutine
// simply vanished via runtime.Goexit without ever returning to the
// Transport that was blocked waiting on it. Handshake failures are
// reported as a plain error instead, which net/http's Transport surfaces
// normally through Get/Do.
func dialTCPTestConn(stack *Stack, clientIP net.IP, clientPort, port uint16) (net.Conn, error) {
	fs := newFakeSession()
	if err := stack.Attach(fs, clientIP); err != nil {
		return nil, fmt.Errorf("dialTCPTestConn: Attach: %w", err)
	}
	tc := &tcpTestClient{
		fs:         fs,
		localIP:    mustAddr(clientIP),
		localPort:  clientPort,
		remoteIP:   mustAddr(stack.ServerIP()),
		remotePort: port,
		isn:        1000,
	}
	tc.sendRaw(tcpSegment{
		srcPort: tc.localPort,
		dstPort: tc.remotePort,
		seq:     tc.isn,
		flags:   flagSYN,
		window:  65535,
		hasMSS:  true,
		mss:     1460,
	})

	synack, ok := tc.tryRecvRaw(2 * time.Second)
	if !ok {
		return nil, errors.New("dialTCPTestConn: timed out waiting for SYN-ACK")
	}
	if synack.flags != flagSYN|flagACK {
		return nil, fmt.Errorf("dialTCPTestConn: SYN-ACK flags = %#x, want SYN|ACK", synack.flags)
	}

	tc.serverISN = synack.seq
	tc.rcvNext = synack.seq + 1
	tc.serverMSS = synack.mss
	tc.sndNext = tc.isn + 1
	tc.sendRaw(tcpSegment{
		srcPort: tc.localPort,
		dstPort: tc.remotePort,
		seq:     tc.sndNext,
		ack:     tc.rcvNext,
		flags:   flagACK,
		window:  65535,
	})

	return newNetTestConn(tc), nil
}

// countingListener wraps a net.Listener and counts successful Accept
// calls — TestHTTPKeepAliveSequence's own assertion that three requests
// over one http.Client's default keep-alive land on a single Accept.
type countingListener struct {
	net.Listener
	accepts atomic.Int64
}

func (l *countingListener) Accept() (net.Conn, error) {
	c, err := l.Listener.Accept()
	if err == nil {
		l.accepts.Add(1)
	}
	return c, err
}

// httpTestHarness runs an unmodified stdlib http.Server directly on
// Stack.ListenTCP's listener (D-01: no wrapper, no adapter) and exposes an
// unmodified stdlib http.Client whose Transport dials fresh netTestConns
// against the same Stack — D-12's fake-Session fast tier, no Docker.
type httpTestHarness struct {
	stack  *Stack
	ln     *countingListener
	client *http.Client

	srv      *http.Server
	serveErr chan error
	seq      atomic.Uint32
}

// newHTTPTestHarness starts srv.Serve on stack.ListenTCP(port) — srv's
// Handler and any timeouts (e.g. ReadHeaderTimeout) are the caller's own —
// and returns a ready-to-use harness. Call h.close() when done.
func newHTTPTestHarness(t *testing.T, port uint16, srv *http.Server) *httpTestHarness {
	t.Helper()
	stack := newTestStack(t)
	rawLn, err := stack.ListenTCP(port)
	if err != nil {
		t.Fatalf("ListenTCP: %v", err)
	}

	h := &httpTestHarness{
		stack:    stack,
		ln:       &countingListener{Listener: rawLn},
		srv:      srv,
		serveErr: make(chan error, 1),
	}
	go func() { h.serveErr <- srv.Serve(h.ln) }()

	h.client = &http.Client{
		Transport: &http.Transport{
			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
				n := h.seq.Add(1)
				// 10.9.x.y, never 10.8.x.y (testServerIP's own /24): a
				// dial must never collide with the server's own tunnel
				// IP (Stack.Attach's own fail-closed check rejects that).
				clientIP := net.IPv4(10, 9, byte(n>>8), byte(n))
				clientPort := uint16(40000 + n)
				return dialTCPTestConn(h.stack, clientIP, clientPort, port)
			},
		},
	}
	return h
}

func (h *httpTestHarness) close() {
	h.srv.Close()
	<-h.serveErr
	h.client.CloseIdleConnections()
	h.stack.Close()
}

// TestHTTPServeOverNetstack is D-01's own success criterion, verbatim:
// stdlib http.Serve, called directly (no wrapper) on stack.ListenTCP's
// result, serves a complete response to a real http.Client — asserted
// through *http.Response, not a raw byte match.
func TestHTTPServeOverNetstack(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("hello from netstack"))
	})

	h := newHTTPTestHarness(t, 8080, &http.Server{Handler: mux})
	defer h.close()

	resp, err := h.client.Get("http://tunnelweb.test/hello")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d, want 200", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "text/plain; charset=utf-8" {
		t.Fatalf("Content-Type = %q, want %q", ct, "text/plain; charset=utf-8")
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("ReadAll: %v", err)
	}
	if string(body) != "hello from netstack" {
		t.Fatalf("body = %q, want %q", body, "hello from netstack")
	}
}

// TestHTTPKeepAliveSequence: three sequential GETs over one http.Client
// (default keep-alive) land on a single accepted TCP connection.
func TestHTTPKeepAliveSequence(t *testing.T) {
	var served atomic.Int64
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		n := served.Add(1)
		_, _ = w.Write([]byte("response "))
		_, _ = w.Write([]byte{'0' + byte(n)})
	})

	h := newHTTPTestHarness(t, 8081, &http.Server{Handler: mux})
	defer h.close()

	for i := 1; i <= 3; i++ {
		resp, err := h.client.Get("http://tunnelweb.test/")
		if err != nil {
			t.Fatalf("Get #%d: %v", i, err)
		}
		body, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			t.Fatalf("ReadAll #%d: %v", i, err)
		}
		want := "response " + string(rune('0'+i))
		if string(body) != want {
			t.Fatalf("body #%d = %q, want %q", i, body, want)
		}
	}

	if n := h.ln.accepts.Load(); n != 1 {
		t.Fatalf("Accept count = %d, want 1 (all three requests should share one keep-alive connection)", n)
	}
}

// TestHTTPLargeResponseBody: a 200KB handler-written response is received
// byte-for-byte, exercising multi-segment delivery, the peer's advertised
// window, and the fixed in-flight cap together.
func TestHTTPLargeResponseBody(t *testing.T) {
	const size = 200 * 1024
	want := make([]byte, size)
	for i := range want {
		want[i] = byte(i)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/big", func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write(want)
	})

	h := newHTTPTestHarness(t, 8082, &http.Server{Handler: mux})
	defer h.close()

	resp, err := h.client.Get("http://tunnelweb.test/big")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()

	got, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("ReadAll: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("response body mismatch: got %d bytes, want %d bytes", len(got), len(want))
	}
}

// TestHTTPLargeRequestBody: a 200KB POST body is fully readable by the
// handler via io.ReadAll(r.Body), exercising multi-segment reassembly on
// the server's receive side.
func TestHTTPLargeRequestBody(t *testing.T) {
	const size = 200 * 1024
	want := make([]byte, size)
	for i := range want {
		want[i] = byte(255 - i%256)
	}

	gotCh := make(chan []byte, 1)
	mux := http.NewServeMux()
	mux.HandleFunc("/upload", func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		gotCh <- body
		w.WriteHeader(http.StatusOK)
	})

	h := newHTTPTestHarness(t, 8083, &http.Server{Handler: mux})
	defer h.close()

	resp, err := h.client.Post("http://tunnelweb.test/upload", "application/octet-stream", bytes.NewReader(want))
	if err != nil {
		t.Fatalf("Post: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d, want 200", resp.StatusCode)
	}

	select {
	case got := <-gotCh:
		if !bytes.Equal(got, want) {
			t.Fatalf("request body mismatch: got %d bytes, want %d bytes", len(got), len(want))
		}
	case <-time.After(5 * time.Second):
		t.Fatal("handler never received the uploaded body")
	}
}

// TestHTTPConnectionCloseCompletes: a request with Connection: close
// returns a complete response and the connection closes cleanly — no RST.
func TestHTTPConnectionCloseCompletes(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte("bye"))
	})

	h := newHTTPTestHarness(t, 8084, &http.Server{Handler: mux})
	defer h.close()

	req, err := http.NewRequest(http.MethodGet, "http://tunnelweb.test/", nil)
	if err != nil {
		t.Fatalf("NewRequest: %v", err)
	}
	req.Close = true

	resp, err := h.client.Do(req)
	if err != nil {
		t.Fatalf("Do: %v", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("ReadAll: %v", err)
	}
	if string(body) != "bye" {
		t.Fatalf("body = %q, want %q", body, "bye")
	}

	// Give the server a moment to finish its own teardown, then confirm no
	// RST was ever needed to close this connection (RESEARCH.md Pitfall 3:
	// a clean half-close, not a reset).
	time.Sleep(50 * time.Millisecond)
	if n := h.stack.TCPStats().RSTsSent; n != 0 {
		t.Fatalf("RSTsSent = %d, want 0 (Connection: close must complete via a clean FIN, not a reset)", n)
	}
}

// TestTCPConnImplementsCloseWriter is a compile-time and runtime proof that
// the value Accept returns satisfies an interface declaring
// CloseWrite() error — mirroring net/http's own unexported closeWriter
// check (net/http/server.go:1772-1787) exactly, since Go interfaces are
// satisfied structurally.
func TestTCPConnImplementsCloseWriter(t *testing.T) {
	stack := newTestStack(t)
	defer stack.Close()
	ln, err := stack.ListenTCP(8085)
	if err != nil {
		t.Fatalf("ListenTCP: %v", err)
	}
	defer ln.Close()

	fs := newFakeSession()
	if err := stack.Attach(fs, testClientAddr()); err != nil {
		t.Fatalf("Attach: %v", err)
	}
	client := newTCPTestClient(t, fs, testClientAddr(), 34567, testServerIP(), 8085)
	client.connect()

	conn, err := acceptWithTimeout(t, ln, time.Second)
	if err != nil {
		t.Fatalf("Accept: %v", err)
	}
	defer conn.Close()

	type closeWriterLike interface {
		CloseWrite() error
	}
	if _, ok := conn.(closeWriterLike); !ok {
		t.Fatalf("Accept's returned net.Conn (%T) does not implement CloseWrite() error", conn)
	}
}

// TestCloseWriteIsHalfClose: after CloseWrite on the accepted conn, the
// test client observes a FIN; the client then sends more data, and the
// server's Read still delivers it; only after the client's own FIN does
// Read return io.EOF. A second CloseWrite is a no-op returning nil.
func TestCloseWriteIsHalfClose(t *testing.T) {
	stack := newTestStack(t)
	defer stack.Close()
	ln, err := stack.ListenTCP(8086)
	if err != nil {
		t.Fatalf("ListenTCP: %v", err)
	}
	defer ln.Close()

	fs := newFakeSession()
	if err := stack.Attach(fs, testClientAddr()); err != nil {
		t.Fatalf("Attach: %v", err)
	}
	client := newTCPTestClient(t, fs, testClientAddr(), 34567, testServerIP(), 8086)
	client.connect()

	conn, err := acceptWithTimeout(t, ln, time.Second)
	if err != nil {
		t.Fatalf("Accept: %v", err)
	}

	cw, ok := conn.(interface{ CloseWrite() error })
	if !ok {
		t.Fatalf("conn (%T) does not implement CloseWrite() error", conn)
	}
	if err := cw.CloseWrite(); err != nil {
		t.Fatalf("CloseWrite: %v", err)
	}

	fin := client.recvRaw(time.Second)
	if fin.flags&flagFIN == 0 {
		t.Fatalf("expected a FIN after CloseWrite, got flags %#x", fin.flags)
	}
	client.rcvNext = fin.seq + 1
	client.sendRaw(tcpSegment{srcPort: client.localPort, dstPort: client.remotePort, seq: client.sndNext, ack: client.rcvNext, flags: flagACK, window: 65535})

	// The read side must still be open: the client sends more data, and
	// the server's Read must still deliver it.
	payload := []byte("still readable after CloseWrite")
	client.sendData(payload)

	got := make([]byte, len(payload))
	if _, err := io.ReadFull(conn, got); err != nil {
		t.Fatalf("Read after CloseWrite: %v", err)
	}
	if !bytes.Equal(got, payload) {
		t.Fatalf("Read after CloseWrite = %q, want %q", got, payload)
	}

	// A second CloseWrite is a no-op returning nil, with no second FIN.
	if err := cw.CloseWrite(); err != nil {
		t.Fatalf("second CloseWrite: %v", err)
	}

	// Now the client sends its own FIN; only then does Read return io.EOF.
	client.sendRaw(tcpSegment{srcPort: client.localPort, dstPort: client.remotePort, seq: client.sndNext, ack: client.rcvNext, flags: flagFIN | flagACK, window: 65535})
	client.sndNext++

	readErrCh := make(chan error, 1)
	go func() {
		_, err := conn.Read(make([]byte, 16))
		readErrCh <- err
	}()
	select {
	case err := <-readErrCh:
		if err != io.EOF {
			t.Fatalf("Read after peer's own FIN = %v, want io.EOF", err)
		}
	case <-time.After(time.Second):
		t.Fatal("Read never returned io.EOF after the peer's own FIN")
	}
}

// TestHTTPIdleKeepAliveDoesNotReset: an http.Server with a short
// ReadHeaderTimeout serving over the netstack, with a client that opens a
// connection and sends nothing, closes that connection without emitting an
// RST storm and without wedging the listener — a second client connects
// and is served normally afterward. This is RESEARCH.md Pitfall 1's own
// warning sign turned into an integration-shaped test: a real net.Error-
// shaped, os.ErrDeadlineExceeded-wrapping timeout is what makes
// ReadHeaderTimeout effective at all on this transport.
func TestHTTPIdleKeepAliveDoesNotReset(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte("ok"))
	})
	h := newHTTPTestHarness(t, 8087, &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: 100 * time.Millisecond,
	})
	defer h.close()

	// First client: connects, sends nothing at all.
	idleFS := newFakeSession()
	if err := h.stack.Attach(idleFS, net.IPv4(10, 8, 0, 200)); err != nil {
		t.Fatalf("Attach: %v", err)
	}
	idleClient := newTCPTestClient(t, idleFS, net.IPv4(10, 8, 0, 200), 44444, testServerIP(), 8087)
	idleClient.connect()

	seg, ok := idleClient.tryRecvRaw(2 * time.Second)
	if !ok {
		t.Fatal("server never closed the idle connection on its own ReadHeaderTimeout")
	}
	if seg.flags&flagRST != 0 {
		t.Fatalf("server reset the idle connection (flags=%#x) instead of a graceful close", seg.flags)
	}

	// Second client: connects after the first idled out and must be
	// served normally — the first client's timeout must not have wedged
	// the listener or the stack.
	resp, err := h.client.Get("http://tunnelweb.test/")
	if err != nil {
		t.Fatalf("Get after idle client's timeout: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status = %d, want 200", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("ReadAll: %v", err)
	}
	if string(body) != "ok" {
		t.Fatalf("body = %q, want %q", body, "ok")
	}
}
