// Command tunnelweb is the canonical example embedding
// github.com/8upio/govpn: it starts a real OpenVPN server, attaches every
// connected session to a privilege-free userspace netstack, and serves a
// small interactive web site entirely through the tunnel — no TUN device,
// no CAP_NET_ADMIN, no process outside this one Go binary, and no OS TCP
// socket bound for HTTP.
//
// Run it:
//
//	go run ./cmd/gentestpki -out /tmp/tunnelweb-pki -profile small
//	go run ./examples/tunnelweb -pki /tmp/tunnelweb-pki
//
// then connect a real OpenVPN client using the generated client config and
// open http://10.8.0.1:8080/ from inside that client's network namespace.
// See README.md for the full walkthrough.
package main

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/binary"
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/8upio/govpn"
	"github.com/8upio/govpn/examples/tunnelweb/site"
	"github.com/8upio/govpn/netstack"
)

func main() {
	pkiDir := flag.String("pki", "", "directory containing ca.crt, server.crt, server.key, tls-crypt.key (generate one with: go run ./cmd/gentestpki -out <dir> -profile small)")
	listenAddr := flag.String("listen", "0.0.0.0:1194", "UDP address the OpenVPN server listens on")
	network := flag.String("network", "10.8.0.0/24", "tunnel IPv4 network clients are assigned from (topology subnet)")
	httpPort := flag.Uint("http-port", 8080, "TCP port the web site listens on, over the netstack — never an OS socket")
	flag.Parse()

	if err := run(*pkiDir, *listenAddr, *network, uint16(*httpPort)); err != nil {
		fmt.Fprintln(os.Stderr, "tunnelweb:", err)
		os.Exit(1)
	}
}

func run(pkiDir, listenAddr, networkCIDR string, httpPort uint16) error {
	if pkiDir == "" {
		return errors.New("missing -pki: generate a PKI first with `go run ./cmd/gentestpki -out <dir> -profile small`, then pass that directory here")
	}

	tlsCfg, tlsCryptKey, err := loadConfig(pkiDir)
	if err != nil {
		return fmt.Errorf("load PKI material from %s (generate one with `go run ./cmd/gentestpki -out %s -profile small` if it's missing): %w", pkiDir, pkiDir, err)
	}

	_, tunnelNetwork, err := net.ParseCIDR(networkCIDR)
	if err != nil {
		return fmt.Errorf("parse -network %q: %w", networkCIDR, err)
	}
	serverIP := firstHostIP(tunnelNetwork)

	// The embedder builds and owns the netstack; nothing in ovpn.Config
	// knows it exists (D-02) — see OnSession below, the load-bearing line
	// of this whole example.
	stack, err := netstack.New(serverIP)
	if err != nil {
		return fmt.Errorf("create netstack: %w", err)
	}
	defer stack.Close()

	ln, err := stack.ListenTCP(httpPort)
	if err != nil {
		return fmt.Errorf("listen tcp :%d over the netstack: %w", httpPort, err)
	}

	httpSrv := &http.Server{Handler: site.Handler(site.Options{
		Cipher:    "AES-256-GCM",
		StartedAt: time.Now(),
	})}
	httpDone := make(chan error, 1)
	go func() { httpDone <- httpSrv.Serve(ln) }()

	pc, err := net.ListenPacket("udp", listenAddr)
	if err != nil {
		return fmt.Errorf("listen udp %s: %w", listenAddr, err)
	}

	srv := ovpn.NewServer(ovpn.Config{
		TLSConfig:   tlsCfg,
		TLSCryptKey: tlsCryptKey,
		Network:     tunnelNetwork,
		Cipher:      "AES-256-GCM",
		OnSession: func(sess *ovpn.Session) {
			// D-02: the embedder attaches; nothing in ovpn.Config knows
			// the netstack exists.
			if err := stack.Attach(sess, sess.AssignedIP()); err != nil {
				log.Printf("warning: netstack attach failed for %s: %v", sess.AssignedIP(), err)
			}
		},
	})

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)

	log.Printf("tunnelweb: network=%s server-tunnel-ip=%s — open http://%s:%d/ from inside a connected client", tunnelNetwork, serverIP, serverIP, httpPort)

	ovpnDone := make(chan error, 1)
	go func() { ovpnDone <- srv.Serve(pc) }()

	select {
	case <-sigCh:
		log.Print("tunnelweb: shutting down")
	case err := <-ovpnDone:
		if err != nil {
			log.Printf("tunnelweb: ovpn server exited: %v", err)
		}
	case err := <-httpDone:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Printf("tunnelweb: http server exited: %v", err)
		}
	}

	_ = srv.Close()
	_ = httpSrv.Close()
	_ = ln.Close()
	return nil
}

// loadConfig reads the PKI material generated by cmd/gentestpki (ca.crt,
// server.crt, server.key, tls-crypt.key) out of pkiDir and builds the
// tls.Config and tls-crypt key ovpn.Config needs.
func loadConfig(pkiDir string) (*tls.Config, []byte, error) {
	caPEM, err := os.ReadFile(pkiDir + "/ca.crt")
	if err != nil {
		return nil, nil, err
	}
	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(caPEM) {
		return nil, nil, fmt.Errorf("no certificates found in %s/ca.crt", pkiDir)
	}

	certPEM, err := os.ReadFile(pkiDir + "/server.crt")
	if err != nil {
		return nil, nil, err
	}
	keyPEM, err := os.ReadFile(pkiDir + "/server.key")
	if err != nil {
		return nil, nil, err
	}
	serverCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return nil, nil, err
	}

	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{serverCert},
		ClientCAs:    caPool,
		ClientAuth:   tls.RequireAndVerifyClientCert,
		MinVersion:   tls.VersionTLS12,
	}

	tlsCryptPEM, err := os.ReadFile(pkiDir + "/tls-crypt.key")
	if err != nil {
		return nil, nil, err
	}
	tlsCryptKey, err := ovpn.ParseStaticKeyV1(tlsCryptPEM)
	if err != nil {
		return nil, nil, err
	}

	return tlsCfg, tlsCryptKey, nil
}

// firstHostIP returns network's first host address (base+1) — the same
// value ippool.go reserves for the library's server-side tunnel address.
func firstHostIP(network *net.IPNet) net.IP {
	ip4 := network.IP.To4()
	base := binary.BigEndian.Uint32(ip4)
	ip := make(net.IP, net.IPv4len)
	binary.BigEndian.PutUint32(ip, base+1)
	return ip
}
